# -*- coding: utf-8 -*-
"""eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mWNl-3krnd4sv67kgexd6IAuYKYYZH2-

## **Exploratory Data Analysis (EDA)**
"""

!pip install pandas pyarrow
import pandas as pd
import numpy as np

file_path = '/content/home_assignment_raw_data.parquet'
df = pd.read_parquet(file_path)

print(df.head())

df.describe()

print(df.info())

# listing the missing values
missing = []
unique = []
types = []
variables = []
count = []

for item in df.columns:
    variables.append(item)
    missing.append(df[item].isnull().sum())
    types.append(df[item].dtypes)
    count.append(len(df[item]))

output = pd.DataFrame({
    'variable': variables,
    'dtype': types,
    'count': count,
    'missing': missing,

})
output.sort_values("missing",ascending=False).reset_index(drop=True)